name: Build Go app and push to Azure

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Copy static view files
      run: xcopy /i view build\views
    
    - name: Copy static css user
      run: xcopy /i view\user\css build\views\user\css

    - name: Copy static js user
      run: xcopy /i view\user\js build\views\user\js

    - name: Copy static css admin
      run: xcopy /i view\admin\css build\views\admin\css

    - name: Copy static js admin
      run: xcopy /i view\admin\js build\views\admin\js

    - name: Copy static image
      run: xcopy /i view\assets\image\products build\views\assets\image\products

    - name: Build
      run: go build .\cmd -o build/go-app.exe -v

    - name: Test
      run: go test
      
    - name: Deploy to Azure
      uses: Azure/webapps-deploy@v2
      with:
        app-name: Shoes-Website
        package: build/
        publish-profile: ${{ secrets.AZURE }}