name: Build Go app and push to Azure

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    # - name: Copy static view files
    #   run: xcopy /i view build\view
    
    # - name: Copy static css user
    #   run: xcopy /i view\user\css build\view\user\css

    # - name: Copy static js user
    #   run: xcopy /i view\user\js build\view\user\js

    # - name: Copy static css admin
    #   run: xcopy /i view\admin\css build\view\admin\css

    # - name: Copy static js admin
    #   run: xcopy /i view\admin\js build\view\admin\js

    # - name: Copy static image
    #   run: xcopy /i view\assets\image\products build\view\assets\image\products
    - name: Copy static view files
      run: cp view build/view

    - name: Copy static css user
      run: cp view/user/css build/view/user/css

    - name: Copy static js user
      run: cp view/user/js build/view/user/js

    - name: Copy static css admin
      run: cp view/admin/css build/view/admin/css

    - name: Copy static js admin
      run: cp view/admin/js build/view/admin/js

    - name: Build
      run: go build -o build/go-app

    - name: Test
      run: go test
      
    - name: Deploy to Azure
      uses: Azure/webapps-deploy@v2
      with:
        app-name: ecommerce-nhom20
        package: build/
        publish-profile: ${{ secrets.AZURE }}